name: Deploy Docs

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Coursier Cache
        uses: coursier/cache-action@v6
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Run SBT docs/mdoc and docs/laikaSite
        run: sbt -v "docs/mdoc; docs/laikaSite"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: target/docs/site
