name: Deploy Docs

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Run SBT docs/mdoc and docs/laikaSite
        run: sbt -v "docs/mdoc; docs/laikaSite"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: target/docs/site
